CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) UNIQUE NOT NULL,
                        year_of_birth int CHECK (year_of_birth >= 1900 AND year_of_birth <= 2022)
);

ALTER TABLE Person ADD COLUMN email varchar(100) UNIQUE NOT NULL;


CREATE TABLE Book (
                      book_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int CHECK ( year>-10000 AND year < 2050),
                      person_id int REFERENCES Person(id) ON DELETE SET NULL
);


ALTER TABLE Book RENAME COLUMN book_id to id;
ALTER TABLE Book RENAME COLUMN name to title;

SELECT * FROM Book;
SELECT * FROM Person;


INSERT INTO Person (full_name, year_of_birth, email) VALUES ('Иванов Иван Иваныч', 1900, 'ivan@ya.ru');
INSERT INTO Person (full_name, year_of_birth, email) VALUES ('Петров Пётр Петрович', 1970, 'petrov@yandex.ru');
INSERT INTO Person (full_name, year_of_birth, email) VALUES ('Алексеев Алексей Алексеевич', 1989, 'aleksej@mail.ru');
INSERT INTO Person (full_name, year_of_birth, email) VALUES ('Васильев Василий Васильевич', 1944, 'vassilij@mail.ru');
INSERT INTO Person (full_name, year_of_birth, email) VALUES ('Николаев Николай Николавеич', 1985, 'kolya@mail.ru');

INSERT INTO Book (title, author, year) VALUES ('Над пропастью во ржи', 'Джером Селинджер', 1951);
INSERT INTO Book (title, author, year) VALUES ('День опричника', 'Владимир Сорокин', 2006);
INSERT INTO Book (title, author, year) VALUES ('Тайные виды на гору Фудзи', 'Виктор Пелевин', 2018);
INSERT INTO Book (title, author, year) VALUES ('Философия Java', 'Брюс Эккель', 2018);
INSERT INTO Book (title, author, year) VALUES ('Психопатология обыденной жизни', 'Зигмунд Фрейд', 1904);
INSERT INTO Book (title, author, year) VALUES ('Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO Book (title, author, year) VALUES ('Бытиё и время', 'Мартин Хайдеггер', 1927);